const Homeproduct =
[
    {
        id: 1,
        Name: 'Samsung TV',
        price: '26',
        image: 'image/p1.webp',
        cat: 'tv',
        type: 'new',
    },
    {
        id: 2,
        Name: 'HP pavilion Laptop',
        price: '96',
        image: 'image/p2.webp',
        cat: 'laptop',
        type: 'new',
    },
    {
        id: 3,
        Name: 'Apple Smartwatch',
        price: '236',
        image: 'image/p3.webp',
        cat: 'watch',
        type: 'new',
    },
    {
        id: 4,
        Name: 'Apple Ipad',
        price: '636',
        image: 'image/p9.jpg',
        cat: 'laptop',
        type: 'new',
    },
    {
        id: 5,
        Name: 'Sony Speaker',
        price: '98',
        image: 'image/p4.webp',
        cat: 'speaker',
        type: 'featured',
    },
    {
        id: 6,
        Name: 'Sony Web Camera',
        price: '59',
        image: 'image/p5.webp',
        cat: 'electronics',
        type: 'featured',
    },
    {
        id: 7,
        Name: 'Philips Headphones',
        price: '956',
        image: 'image/p10.jpg',
        cat: 'headphone',
        type: 'featured',
    },
    {
        id: 8,
        Name: 'Stopwatch',
        price: '389',
        image: 'image/p11.jpg',
        cat: 'electronics',
        type: 'featured',
    },
    {
        id: 9,
        Name: 'Redmi 10 Mobile',
        price: '67',
        image: 'image/p6.webp',
        cat: 'phone',
        type: 'top',
    },
    {
        id: 10,
        Name: ' Philips speaker',
        price: '76',
        image: 'image/p7.webp',
        cat: 'speaker',
        type: 'top',
    },
    {
        id: 11,
        Name: 'JBL Black Ultra',
        price: '87',
        image: 'image/p8.webp',
        cat: 'speaker',
        type: 'top',
    },
    {
        id: 12,
        Name: 'Portronics Dash ',
        price: '807',
        image: 'image/p12.jpg',
        cat: 'speaker',
        type: 'top',
    },
]
export default Homeproduct